name: Node.js CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          # 分别缓存前后端 lock 文件（如果其中一个不存在也不会报错）
          cache-dependency-path: |
            frontend/package-lock.json
            backend/package-lock.json

      # ========== FRONTEND ==========
      - name: Install Frontend deps
        if: ${{ hashFiles('frontend/package.json') != '' }}
        working-directory: ./frontend
        run: npm ci

      - name: Build Frontend
        if: ${{ hashFiles('frontend/package.json') != '' }}
        working-directory: ./frontend
        run: npm run build

      # ========== BACKEND ==========
      - name: Install Backend deps
        if: ${{ hashFiles('backend/package.json') != '' }}
        working-directory: ./backend
        run: npm ci

      - name: Build Backend
        if: ${{ hashFiles('backend/package.json') != '' }}
        working-directory: ./backend
        run: npm run build

      - name: Test Backend (optional)
        if: ${{ hashFiles('backend/package.json') != '' }}
        working-directory: ./backend
        run: |
          npm test || echo "No tests configured yet"
